// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gamestate

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerStateUpdate struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerStateUpdate(buf []byte, offset flatbuffers.UOffsetT) *PlayerStateUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerStateUpdate{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlayerStateUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlayerStateUpdate(buf []byte, offset flatbuffers.UOffsetT) *PlayerStateUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerStateUpdate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlayerStateUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlayerStateUpdate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerStateUpdate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerStateUpdate) Timestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerStateUpdate) MutateTimestamp(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *PlayerStateUpdate) ClientId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerStateUpdate) MutateClientId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *PlayerStateUpdate) PlayerState(obj *PlayerState) *PlayerState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PlayerState)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PlayerStateUpdateStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PlayerStateUpdateAddTimestamp(builder *flatbuffers.Builder, timestamp int64) {
	builder.PrependInt64Slot(0, timestamp, 0)
}
func PlayerStateUpdateAddClientId(builder *flatbuffers.Builder, clientId uint32) {
	builder.PrependUint32Slot(1, clientId, 0)
}
func PlayerStateUpdateAddPlayerState(builder *flatbuffers.Builder, playerState flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(playerState), 0)
}
func PlayerStateUpdateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
